#!/bin/bash

if [ "$1" = "-gpg" ] && [ "$#" = 2 ]; then

	gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $2
	gpg --list-keys
	echo "Quizá quierar ejecutar: $0 -apt <keyUID>"

elif [ "$1" = "-apt" ] && [ "$#" = 2 ]; then

	gpg --armor -o keyfile131924 --export $2
	cat keyfile131924
	sudo apt-key add keyfile131924
	rm -f keyfile131924 

else
	echo "usage: $0 -gpg <keyToInstall>"
	echo "usage: $0 -apt <keyUID>"
fi
