#!/bin/bash

process="tomcat"

#inspired by ps aux | sed -n '/tomcat/{/grep/!p;}' | awk '{print$2}' | xargs -i kill {}
pid=`ps aux | grep $process | grep -v grep | awk '{print $2}'`

if [ $pid ]; then
	echo "Matando a tomcat...con pid $pid"
	kill -9 $pid
else
	echo "$process no está corriendo en este momento.";
fi
