engines:
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
  - "dotfiles/.*"
  - "scripts/**"
  - "scripts/**/**"
  - "scripts/**/**/*"
  - "**.sh"
  - "**.zsh"
  - "**.yml"
  - "**.md"

exclude_paths: []
