#!/bin/bash

# sandbin installation directory
export SANDBIN_HOME=`dirname $0`

# Load sandbin configuration
source "$SANDBIN_HOME/sandbin.conf"

# export sandbin paths
source "$SANDBIN_HOME/dotfiles/.paths"

# source dotfiles
source "$SANDBIN_HOME/dotfiles/.functions"
