#!/bin/bash

usage() {
	echo -e "usage: ./git-init.sh [--system|--global|--local] \"User Name\" user@name.es"
}

if [ $# -lt 3 ]; then
	usage
	exit 1
fi

scope=$1
username=$2
email=$3

set -e

echo -e "Configuring username and email as repository properties..."
git config $scope user.name "$username"
git config $scope user.email "$email"
