#!/bin/bash

usage() {
	echo -e "usage: ./git-init.sh [--system|--global|--local] \"User Name\" user@name.es"
}

if [ $# -lt 3 ]; then
	usage
	exit 1
fi

scope=$1
username=$2
email=$3

set -e

echo -e "Configuring username and email as repository properties..."
git config $scope user.name "$username"
git config $scope user.email "$email"

echo -e "Configuring aliases for log command..."

echo -e "New command: git lol"
git config $scope alias.lol "log --pretty=oneline --abbrev-commit --graph --decorate"

echo -e "New command: git changelog"
#git config alias.changelog "log --pretty=oneline --abbrev-commit --decorate --color"
git config $scope alias.changelog "log `git describe --tags --abbrev=0`..HEAD --pretty=format:\"  * [%h] %s\" --reverse --no-merges"
# TODO: See if it's possible to stop in previous release
#git log v2.1.0...v2.1.1 --pretty=format:'<li> <a href="http://github.com/jeslopalo/<project>/commit/%H">view commit &bull;</a> %s</li> ' --reverse | grep "#changelog"

echo -e "New command: git authors"
git config $scope alias.authors '!git log --all --format="%aN <%aE>" | sort -u'

echo -e "Configuring aliases for unstage changes..."
git config $scope alias.unstage "reset HEAD"
