#!/bin/bash

usage() {
	echo -e "usage: ./git-aliases [--system|--global|--local]"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

# Use colors, but only if connected to a terminal, and that terminal
# supports them.
tput=$(which tput)
if [ -n "$tput" ]; then
    ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
  YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"
  NORMAL="$(tput sgr0)"
else
  YELLOW=""
  BLUE=""
  NORMAL=""
fi

scope=$1

function new_alias() {
  local alias_name=$1
  local alias_command=$2

  echo -e "New command: ${YELLOW}git ${alias_name}${NORMAL}"
  git config $scope alias.${alias_name} "${alias_command}"
}
set -e

echo -e "${BLUE}Configuring aliases for aliases...${NORMAL}"
new_alias "alias" "!git config --get-regexp 'alias.*' | colrm 1 6 | sed 's/[ ]/=\t/'"
new_alias "clean-alias" "config $scope --remove-section alias"

echo -e "${BLUE}Configuring aliases for history...${NORMAL}"
new_alias "history" "log --graph --pretty=format:'%Cred%h%Creset %C(bold blue)<%ae>%Creset %Cgreen(%cr)%Creset %C(auto)%d%Creset - %s' --abbrev-commit --date=relative --decorate --color"
new_alias "history-all" "!git history --all"
new_alias "history-of" "!git history --first-parent"

echo -e "${BLUE}Configuring aliases for authors...${NORMAL}"
new_alias "authors" '!git log --all --format="%aN <%aE>" | sort -u'

echo -e "${BLUE}Configuring aliases for changes...${NORMAL}"
new_alias "changelog" "!f() { git last-tag | xargs -I tag git log tag..HEAD --pretty=format:\"  * [%h] %s\" --reverse --no-merges; }; f"
new_alias "changes" "diff --name-status -r"
new_alias "diffstat" "diff --stat -r"

echo -e "${BLUE}Configuring aliases for branches...${NORMAL}"
new_alias "branches" "!git for-each-ref --sort='-authordate' --format='%(authordate) - %(refname)' refs/heads | sed -e 's-refs/heads/--'"
new_alias "branches-last-commit" "branch -vv -a"

echo -e "${BLUE}Configuring aliases for tags...${NORMAL}"
new_alias "last-tag" "describe --tags --abbrev=0"

echo -e "${BLUE}Configuring aliases for commits...${NORMAL}"
new_alias "last-commit" "diff --cached HEAD^"

echo -e "${BLUE}Configuring aliases for stages...${NORMAL}"
new_alias "unstage" "reset HEAD --"

echo -e "${BLUE}Configuring aliases for push changes...${NORMAL}"
new_alias "push-all" "!git push --all && git push --tags"

echo -e "${BLUE}Configuring aliases for remotes...${NORMAL}"
new_alias "show-origin" "remote show origin"

echo -e "${BLUE}Configuring aliases to set config values...${NORMAL}"
new_alias "filemodeon" "config --local core.filemode true"
new_alias "filemodeoff" "config --local core.filemode false"