#!/bin/bash

usage() {
	printf "${YELLOW}%s${NORMAL}\n" "usage: git-init [--system|--global|--local] \"User Name\" user@name.es"
}

if [ $# -lt 3 ]; then
	usage
	exit 1
fi

scope=$1
username=$2
email=$3

#Fonts format
outpututils_bold=`tput bold`
outpututils_normal=`tput sgr0`

function b() {
	echo "$outpututils_bold$1$outpututils_normal"
}

set -e

echo -e "Configuring username $(b "$username") & email $(b "$email") as $(b "$scope") repository properties..."
git config $scope user.name "$username"
git config $scope user.email "$email"
