#!/usr/bin/env bash

function yaml_export {
    local filepath=$1
    local prefix=$2
    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
    sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $filepath |
    awk -F$fs '{
        indent = length($1)/2;
        vname[indent] = $2;
        for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=\"%s\"\n", "'$prefix'", vn, $2, $3);
            printf("%s%s%s=\"%s\"\n", "'$prefix'", tolower(vn), tolower($2), $3);
            printf("%s%s%s=\"%s\"\n", "'$prefix'", toupper(vn), toupper($2), $3);
        }
    }'
}

if [ $# = 0 ]; then
    printf "${RED}yaml_export: Sorry! I need a yaml file to continue :(${NORMAL}\n" 1>&2
    exit 1;
fi

yaml_export $@ | uniq

#$ ./yaml_export ~/Development/utilities/sandbin/tests/yaml/test.yml | xargs -I {} echo "export {}"
