#!/bin/zsh

if [ ! -n "$SANDBIN_HOME" ] || [ ! -d "$SANDBIN_HOME" ]; then
	echo "${RED}You have not sandbin installed. You'll need to install sandbin${NORMAL}" 1>&2
    exit 1
fi

# shellcheck source=scripts/lib/lang.lib.zsh
source "$SANDBIN_HOME/scripts/lib/lang.lib.zsh"

import "scripts/lib/output.lib.zsh"
import "scripts/lib/colors.lib.zsh"

script_name=$1
if [ -z "$script_name" ]; then
    echo "${RED}sandbash: The name of script is mandatory.${NORMAL}" 1>&2
    exit 1
fi

shift

source $script_name "$@"
