#!/bin/bash

set -e

if [ ! -n "$SANDBIN_HOME" ] || [ ! -d "$SANDBIN_HOME" ]; then
	echo "${RED}You have not sandbin installed. You'll need to install sandbin${NORMAL}"
    exit 1
fi

source "$SANDBIN_HOME/scripts/lib/output.lib.bash"
source "$SANDBIN_HOME/scripts/lib/colors.lib.bash"
source "$SANDBIN_HOME/scripts/lib/sandbin.lib.bash"

script_name=$1
if [ -z "$script_name" ]; then
    echo "${RED}sandbash: The name of script is mandatory.${NORMAL}"
    exit 1
fi

shift

source $script_name "$@"